### ISSUE TITLE
Implement events hub

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/dthm4kaiako#296]
This task reimplements the event hub, based off the learnings from cs4teachers, and other projects.

## Todo

- [x] Implement event model
  - [x] Allow events to be with or without sessions
  - [x] Research https://django-scheduler.readthedocs.io/en/latest/index.html and https://github.com/dakrauth/django-swingtime
- [x] Implement session model
- [x] Implement organiser model
- [x] Implement sponsor model
- [x] Implement location model
  - [x] Use GIS enabled database.
- [x] Implement series model
- [x] Implement views

**Comment by JackMorganNZ** [comment]
Basic version implemented in 19cc748962787a294b2b59c6d44a3dfb1676b885
