### ISSUE TITLE
Add bitfit resource

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/dthm4kaiako#333]
This issue adds the prototype bitfit application into the website. There is some major changes to occur including using the existing user system, and changing from testing on Sphere Engine to testing locally in JavaScript. Therefore the application will be stripped down to it's core components, in order to be released as soon as possible.

## Todo

*This will be an incomplete list, but used to adding tasks as they are encountered. Tasks may be moved to future issues.*

- [x] Use existing user model.
- [x] Use JS (Skulpt) for running Python code.
- [x] Store all test case data within JavaScript object.
- [x] Handle infinite loops.
- [x] Store attempt data in database.
- [x] Prefill page with last user attempt.
- [ ] Handle JS errors for questions gracefully, prompt bug report.
- [ ] Prompt user to login to store attempts.
- [x] Store results for each test for an attempt.
- [ ] Order test cases (normal, boundary, exceptional)
- [ ] Prevent running of code when loading page or running code.
- [ ] Provide feedback on running tests, loading previous attempts, etc.
- [x] Store questions in repository and load questions on update (possibly store by slug rather than id).
- [ ] Run threads asynchronously to allow browser responsiveness, while handling infinite loops:
  - https://github.com/skulpt/skulpt/issues/357
  - https://github.com/skulpt/skulpt/pull/470#issueco<kbd>24</kbd>mment-120626639

## Changes from prototype

- Now saves all user attempts, previously saved only last attempt. Removed save button, user can't save code without running it now, but this simplifies the process (both for backend and user).
- Remove point scoring for attempting question (up to three points).

## Notes

- The system tracks the days the user logged into the system (though a view mixin). Would it be better to store the days the user attempted/solved a question?
- Previous system didn't allow `sep` parameter for `print()`, but Skulpt has this functionality.

**Comment by JackMorganNZ** [comment]
Completed with codeWOF repository.
